config/routes.rb
Rails.application.routes.draw do



  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/new_user', to: 'users#new'
  post '/new_user', to: 'users#create'
  get 'users/show'
  get 'users/index'
  root 'static_pages#home'

  get 'subreddits/show'
  get 'subreddits/new'
  get 'subreddits/index'


  resources :subreddits do
    resources :posts do
      resources :comments
    end
  end

  resources :users do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :comment, presence: true, length: { maximum: 256 }

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :subreddit
  has_many :comments

  validates :subreddit_id, presence: true
  validates :content, presence: true
end

app/models/subreddit.rb
class Subreddit < ApplicationRecord
  validates :name, presence: true, length: { maximum: 255, minimum: 2 }
  has_many :posts

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2, maximum: 63 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { minimum: 5, maximum: 255 },
                          format: { with: VALID_EMAIL_REGEX }
  #validates :password_digest, presence: true
  has_secure_password

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.create(comment_params)
    @comment.post_id = params[:post_id]

    if !current_user.nil?
      @comment.user_id = current_user.id
      @comment.updoots = 0

      if @comment.save
        redirect_to subreddit_post_path(params)
      else
        # Say error
      end
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:comment, :user_id, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @subreddit = Subreddit.find(params[:subreddit_id])
    @comments = Comment.all
  end

  def create
    @post = Post.new(post_params)
    @post.subreddit_id = params[:subreddit_id]
    @post.updoots = 0

    # If user isn't logged in, don't allow to post
    if !current_user.nil?
      @post.user_id = current_user.id

      if @post.save
        redirect_to Subreddit.find(params[:subreddit_id])
      else
        # Do something else
      end
    else
      # Flash something
    end
  end


  private

    def post_params
      params.require(:post).permit(:content, :title)
    end

    def comment_params
      params.require(:comment).permit(:comment, :user_id, :post_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      render 'new'
    end
  end

  def destroy
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end


end

app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController
  def new
    @subreddit = Subreddit.new
  end

  def show
    @subreddit = Subreddit.find(params[:id])
    @posts = Subreddit.find(params[:id]).posts
  end

  def index
    @subreddits = Subreddit.all
  end

  def create
    @subreddit = Subreddit.new(subreddit_params)
    if @subreddit.save
      redirect_to @subreddit
    else
      #do something
    end
  end

  private

    def subreddit_params
      params.require(:subreddit).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      # Do something else
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :pasword_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs the user in
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subreddits_helper.rb
module SubredditsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="comment-box">
  <%= form_for @comment,  url: { action: "create"} do |f| %>
    Comment: <%= f.text_area :comment %>
    <%= f.submit "Post comment" %>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-dark bg-dark">
  <div class="container navbar">
    <p id="nav-home-link"><%= link_to "Home", root_url %></p>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <ul class="navbar navbar-nav ">
        <li class="nav-item"><%= link_to "Subreddits", subreddits_index_url %></li>
        <li class="nav-item"><%= link_to "Users", users_index_url %></li>
        <li class="nav-item"><%= link_to "Login", login_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <title><%= yield(:title) %> | Rails Reddit Clone</title>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/new.html.erb
<h1>Create New Post</h1>

<div class="container">
  <%= form_for @post, url: {action: "create"} do |f| %>
    Title: <%= f.text_field :title, class: "form-control" %>
    Message: <%= f.text_area :content, class: "form-control" %>
    <%= f.submit "new post", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<h1><%= link_to @subreddit.name, @subreddit %></h1>
<h1><%= @post.title %></h1>

<div class="container">
  <%= @post.content %>
</div>

<%= link_to "New Comment", new_subreddit_post_comment_path(@subreddit, @post) %>

<ul class="comments">
  <% @comments.each do |c| %>
    <li><%= c.comment %></li>
  <% end %>
</ul>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
  <body>
    <h1>Home</h1>

    <%= link_to "Create an account", new_user_path %>
  </body>
</html>

app/views/subreddits/index.html.erb
<% provide(:title, "Subreddits") %>

<h1>List of subreddits</h1>

<%= link_to "Create Subreddit", subreddits_new_path %>

<% @subreddits.each do |s| %>
  <p><%= link_to s.name, s %></p>
<% end %>

app/views/subreddits/new.html.erb
<%= provide(:button_text, "create subreddit") %>
<% provide(:title, "New Subreddit") %>

<h1>New Subreddit</h1>

<%= form_for(@subreddit) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/subreddits/show.html.erb
<h1><%= @subreddit.name %></h1>

<%= link_to "New post", new_subreddit_post_path(@subreddit) %>

<div class="container">
  <ul style="list-style-type:none;" class="list-group post-list">
    <% @posts.each do |p| %>
      <li class="list-group-item post">

        <div class="container title">
          <p class="post-updoots"><%= p.updoots %>&uarr;</p>
          <h6 class="post-link">@<%= @subreddit.name %> -</h6>
          <h6 class="post-title"><%= link_to p.title.to_s, url_for([@subreddit, p]) %></h6>
        </div>
        <p class="post-content"><%= p.content %></p>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/index.html.erb
<h1>Users Index</h1>

<%= link_to "Add user", new_user_url %>

<div class="container">
  <ul>
    <% @users.each do |user| %>
      <li>
        <%= link_to user.name, user %>
        <%= user.email %>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/new.html.erb
<% provide(:title, "New User") %>

<h1>New User</h1>

<div class="container">
  <%= form_for @user, url: {action: "create" } do |f| %>
    Name: <%= f.text_field :name, class: "form-control" %>
    Email: <%= f.text_field :email, class: "form-control" %>
    Password: <%= f.password_field :password, class: "form-control" %>
    Password confirmation: <%= f.password_field :password_confirmation, class: "form-control" %>
    <%= f.submit %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>